#!/bin/sh -x
g++ -D_FILE_OFFSET_BITS=64 -DFREEARC_64BIT -DFREEARC_UNIX -DFREEARC_INTEL_BYTE_ORDER -O3 --param inline-unit-growth=999 -funroll-loops -fno-exceptions -fno-rtti -fomit-frame-pointer -fstrict-aliasing -ffast-math -fforce-addr -fwhole-program -combine -lrt "$@" main.cpp -s -otor
# -DSTATS -DDEBUG -DFULL_COMPILE -DFREEARC_NO_TIMING
